# Generated by Django 6.0.5 on 2026-05-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rh', models.CharField(max_length=50, unique=True, verbose_name='Id RH')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('fec_ingreso', models.DateField(blank=True, null=True, verbose_name='Fec. Ingreso')),
                ('nro_documento', models.CharField(max_length=20, verbose_name='Nº de documento')),
                ('convenio', models.CharField(blank=True, max_length=150, verbose_name='Convenio')),
                ('nombre_posicion', models.CharField(blank=True, max_length=150, verbose_name='Nombre posición')),
                ('nombre_area', models.CharField(blank=True, max_length=150, verbose_name='Nombre de Area')),
                ('nombre_unidad_org', models.CharField(blank=True, max_length=150, verbose_name='Nombre unidad org.')),
                ('fec_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fec. Nacimiento')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
