# Generated by Django 6.0.5 on 2026-05-30 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='instruccion',
            field=models.CharField(blank=True, choices=[('SIN_INSTRUCCION', 'Sin instrucción'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICA', 'Técnica'), ('SUPERIOR', 'Superior'), ('POSGRADO', 'Posgrado')], max_length=20, verbose_name='Instrucción'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de atención')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('sistolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Sistólica')),
                ('diastolica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Diastólica')),
                ('abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Abdominal (cm)')),
                ('icc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ICC')),
                ('colesterol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Colesterol Total')),
                ('hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='HDL Colesterol')),
                ('ldl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='LDL Colesterol')),
                ('vldl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VLDL Colesterol')),
                ('trigliceridos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Triglicéridos')),
                ('hemoglobina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hemoglobina')),
                ('hematocrito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hematocrito')),
                ('glucosa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Glucosa')),
                ('hb_a1c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HB A1c')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha', 'paciente__nombre_completo'],
            },
        ),
    ]
