# Generated by Django 6.0.5 on 2026-05-30 22:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_instruccion_paciente_sexo_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de atención')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Grasa corporal')),
                ('grasa_visceral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Grasa visceral')),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Masa muscular')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones_nutricion', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Atención de nutrición',
                'verbose_name_plural': 'Atenciones de nutrición',
                'ordering': ['-fecha', 'paciente__nombre_completo'],
            },
        ),
    ]
