# Generated by Django 6.0.5 on 2026-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_atencionnutricion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
    ]
