# Generated by Django 6.0.5 on 2026-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, help_text='Si se deja vacío se estima a partir de departamento/distrito.', null=True, verbose_name='Altitud (msnm)'),
        ),
    ]
