# Generated by Django 6.0.5 on 2026-06-02 21:47

from django.db import migrations, models


def backfill_altitud_cache(apps, schema_editor):
    """Llena altitud_cache para todos los pacientes ya existentes."""
    from pacientes.peru_altitudes import altitud_estimada

    Paciente = apps.get_model("pacientes", "Paciente")
    actualizados = []
    for p in Paciente.objects.all().iterator():
        if p.altitud_msnm is not None:
            p.altitud_cache = p.altitud_msnm
        else:
            p.altitud_cache = altitud_estimada(p.distrito, p.provincia, p.departamento)
        actualizados.append(p)
    Paciente.objects.bulk_update(actualizados, ["altitud_cache"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_altitud_msnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altitud_cache',
            field=models.IntegerField(blank=True, db_index=True, editable=False, help_text='Altitud efectiva precalculada para filtros. Se llena en save().', null=True, verbose_name='Altitud efectiva (cache)'),
        ),
        migrations.RunPython(backfill_altitud_cache, reverse_code=migrations.RunPython.noop),
    ]
